#!/usr/bin/env python3
"""Build ~/s, a locked symlink farm that gives a browsable view of ~/src.

Every non-hidden top-level entry of the source directory gets exactly one link
in the topic tree (placed by layout.conf) plus links in the generated by-owner/
and by-kind/ views. A link always carries the entry's own name and an absolute
target, so the last path component of anything in the farm is its ~/src name.

Between runs every real directory in the farm is mode 0555 with the BSD
user-immutable flag (uchg) set, so nothing else can add, remove or rename
entries. Driven by the justfile next to this file; see AGENTS.md.
"""

import argparse
import fnmatch
import os
import re
import stat
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
XATTR = "com.djbclark.sfarm"
XATTR_NOTE = "generated symlink view of {src}; locked; update with: just -f {farm}/justfile"
# Links in the farm root that point at this tool rather than into the source.
STATIC = {"AGENTS.md": HERE / "AGENTS.md", "CLAUDE.md": "AGENTS.md", "justfile": HERE / "justfile"}
VIEWS = ("by-owner", "by-kind")
FILES_DEST = "files"
UNSORTED_DEST = "unsorted"
WORKTREES_SUFFIX = re.compile(r"[-.]worktrees$")


class Entry:
    def __init__(self, path):
        self.path = path
        self.name = path.name
        self.kind, self.parent, self.owner = classify(path)


def classify(path):
    """Return (kind, worktree parent name or None, origin owner or None)."""
    if path.is_symlink():
        return "link", None, None
    if not path.is_dir():
        return "file", None, None
    dotgit = path / ".git"
    if dotgit.is_dir():
        return "repo", None, origin_owner(dotgit)
    if dotgit.is_file():
        common = common_git_dir(dotgit)
        if common is None:
            return "worktree", None, None
        # .../<repo>/.git -> <repo>; .../.git/modules/<sub> -> <sub>
        parent = common.parent.name if common.name == ".git" else common.name
        return "worktree", parent, origin_owner(common)
    return "dir", None, None


def common_git_dir(gitfile):
    """Follow a worktree's .git file to the repository's shared git directory."""
    try:
        m = re.match(r"gitdir:\s*(.+)", gitfile.read_text().strip())
        if not m:
            return None
        gitdir = (gitfile.parent / m.group(1)).resolve()
        commondir = gitdir / "commondir"
        if commondir.is_file():
            return (gitdir / commondir.read_text().strip()).resolve()
        return gitdir
    except OSError:
        return None


def origin_owner(gitdir):
    """Owner segment of the origin remote URL, read straight from the config."""
    try:
        text = (gitdir / "config").read_text(errors="replace")
    except OSError:
        return None
    section = re.search(r'^\[remote "origin"\]\n((?:[ \t].*\n?)*)', text, re.M)
    url = section and re.search(r"^\s*url\s*=\s*(\S+)", section.group(1), re.M)
    m = url and re.search(r"[:/]([^/:]+)/[^/]+?/?$", url.group(1))
    return m.group(1) if m else None


def read_layout(path):
    """Parse 'dest/dir: glob glob ...' lines into an ordered rule list."""
    rules = []
    for n, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        dest, sep, globs = line.partition(":")
        dest = dest.strip().strip("/")
        if not sep or not dest or not globs.split():
            sys.exit(f"{path}:{n}: expected 'dest/dir: pattern ...'")
        top = dest.split("/")[0]
        if top in VIEWS or top in STATIC or any(p in ("", ".", "..") for p in dest.split("/")):
            sys.exit(f"{path}:{n}: destination '{dest}' is reserved or invalid")
        rules.append((dest, globs.split()))
    return rules


def place(entries, rules):
    """Map each entry name to its topic directory; return (dest by name, unsorted names)."""
    dest = {}
    for e in entries:
        for d, globs in rules:
            if any(fnmatch.fnmatchcase(e.name, g) for g in globs):
                dest[e.name] = d
                break
    # Entries without a rule follow the repo they belong to, so a new worktree
    # or '<repo>-worktrees' directory lands beside its parent on its own.
    unsorted = []
    for e in entries:
        if e.name in dest:
            continue
        base = WORKTREES_SUFFIX.sub("", e.name)
        if e.kind == "worktree" and e.parent in dest:
            dest[e.name] = dest[e.parent]
        elif base != e.name and base in dest:
            dest[e.name] = dest[base]
        elif e.kind == "file":
            dest[e.name] = FILES_DEST
        else:
            dest[e.name] = UNSORTED_DEST
            unsorted.append(e.name)
    return dest, unsorted


def desired_links(src, layout):
    """Return ({farm-relative link path: target}, unsorted names)."""
    entries = sorted(
        (Entry(p) for p in src.iterdir() if not p.name.startswith(".")),
        key=lambda e: e.name.lower(),
    )
    dest, unsorted = place(entries, read_layout(layout))
    links = {name: str(target) for name, target in STATIC.items()}
    for e in entries:
        target = str(e.path)
        links[f"{dest[e.name]}/{e.name}"] = target
        if e.kind in ("repo", "worktree"):
            links[f"by-owner/{e.owner or '_no-remote'}/{e.name}"] = target
        if e.kind == "worktree":
            links[f"by-kind/worktree/{e.parent or '_unknown'}/{e.name}"] = target
        else:
            links[f"by-kind/{e.kind}/{e.name}"] = target
    check_collisions(links)
    return links, unsorted


def check_collisions(links):
    """A name cannot be both a link and a directory, nor differ only by case (APFS)."""
    seen = {}
    for rel in links:
        parts = rel.split("/")
        for i in range(1, len(parts) + 1):
            prefix = "/".join(parts[:i])
            role = "link" if i == len(parts) else "dir"
            key = prefix.casefold()
            if key in seen and seen[key] != (prefix, role):
                sys.exit(
                    f"layout collision: '{prefix}' ({role}) clashes with "
                    f"'{seen[key][0]}' ({seen[key][1]}); change layout.conf"
                )
            seen[key] = (prefix, role)


def real_dirs(farm):
    """Every real directory in the farm, root first (symlinks are never followed)."""
    out = []
    for root, dirs, _ in os.walk(farm, followlinks=False):
        out.append(Path(root))
        dirs[:] = [d for d in dirs if not (Path(root) / d).is_symlink()]
    return out


def set_locked(farm, locked):
    # The mode can only change while the flag is clear, hence the two orders.
    for d in real_dirs(farm):
        flags = os.lstat(d).st_flags
        if locked:
            os.chmod(d, 0o555)
            os.chflags(d, flags | stat.UF_IMMUTABLE)
        else:
            os.chflags(d, flags & ~stat.UF_IMMUTABLE)
            os.chmod(d, 0o755)


def is_locked(path):
    return bool(os.lstat(path).st_flags & stat.UF_IMMUTABLE)


def marker(farm):
    r = subprocess.run(["xattr", "-p", XATTR, str(farm)], capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 else None


def scan(farm, src):
    """Return (managed links {rel: target}, foreign rel paths, real dir rel paths)."""
    managed, foreign, dirs = {}, [], []
    static_targets = {str(t) for t in STATIC.values()}
    for d in real_dirs(farm):
        if d != farm:
            dirs.append(str(d.relative_to(farm)))
        for child in sorted(d.iterdir()):
            rel = str(child.relative_to(farm))
            if child.is_symlink():
                target = os.readlink(child)
                if target.startswith(f"{src}/") or target in static_targets or rel in STATIC:
                    managed[rel] = target
                else:
                    foreign.append(rel)
            elif not child.is_dir():
                foreign.append(rel)
    return managed, foreign, dirs


def diff(farm, src, layout):
    want, unsorted = desired_links(src, layout)
    have, foreign, dirs = scan(farm, src) if farm.is_dir() else ({}, [], [])
    add = {r: t for r, t in want.items() if have.get(r) != t}
    remove = [r for r, t in have.items() if want.get(r) != t]
    want_dirs = {"/".join(r.split("/")[:i]) for r in want for i in range(1, r.count("/") + 1)}
    stale_dirs = [d for d in dirs if d not in want_dirs]
    return want, add, remove, stale_dirs, foreign, unsorted


def guard(farm, src):
    """Refuse to take over a directory this tool did not create."""
    if not farm.exists():
        return
    if marker(farm) is None and any(farm.iterdir()):
        _, foreign, dirs = scan(farm, src)
        if foreign or dirs:
            sys.exit(
                f"{farm} is not empty and is not marked as a farm ({XATTR} xattr missing); "
                "refusing to touch it. Move its contents away first."
            )


def report(add, remove, stale_dirs, foreign, unsorted, verb):
    for r in sorted(remove):
        print(f"  - {r}")
    for r in sorted(add):
        print(f"  + {r} -> {add[r]}")
    for d in sorted(stale_dirs):
        print(f"  - {d}/")
    print(f"{verb}: +{len(add)} links, -{len(remove)} links, -{len(stale_dirs)} dirs")
    if unsorted:
        print(f"no layout rule (placed in {UNSORTED_DEST}/): {' '.join(sorted(unsorted))}")
        print(f"  add them to {HERE / 'layout.conf'}")
    if foreign:
        print("foreign entries (not created by this tool, left alone):")
        for r in foreign:
            print(f"  ! {r}")


def cmd_update(farm, src, layout):
    guard(farm, src)
    want, add, remove, stale_dirs, foreign, unsorted = diff(farm, src, layout)
    farm.mkdir(exist_ok=True)
    set_locked(farm, False)
    try:
        for rel in remove:
            (farm / rel).unlink()
        for rel in sorted(stale_dirs, key=len, reverse=True):
            try:
                (farm / rel).rmdir()
            except OSError:
                foreign.append(f"{rel}/ (not empty)")
        for rel, target in add.items():
            link = farm / rel
            link.parent.mkdir(parents=True, exist_ok=True)
            if link.is_symlink() or link.exists():
                foreign.append(f"{rel} (blocks a link)")
                continue
            os.symlink(target, link)
        note = XATTR_NOTE.format(src=src, farm=farm)
        subprocess.run(["xattr", "-w", XATTR, note, str(farm)], check=True)
    finally:
        set_locked(farm, True)
    report(add, remove, stale_dirs, foreign, unsorted, "updated")
    print(f"{farm}: {len(want)} links, locked")


def cmd_plan(farm, src, layout, check):
    _, add, remove, stale_dirs, foreign, unsorted = diff(farm, src, layout)
    report(add, remove, stale_dirs, foreign, unsorted, "plan")
    unlocked = [d for d in real_dirs(farm) if not is_locked(d)] if farm.is_dir() else []
    if unlocked:
        print(f"UNLOCKED: {len(unlocked)} director(ies), e.g. {unlocked[0]}")
    if check and (add or remove or stale_dirs or unlocked):
        sys.exit(1)


def cmd_status(farm, src, layout):
    if not farm.is_dir():
        sys.exit(f"{farm} does not exist; run the update first")
    dirs = real_dirs(farm)
    locked = sum(is_locked(d) for d in dirs)
    have, foreign, _ = scan(farm, src)
    dangling = [r for r in have if not (farm / r).exists()]
    print(f"farm    {farm}")
    print(f"source  {src}")
    print(f"layout  {layout}")
    print(f"marker  {marker(farm) or 'MISSING'}")
    print(f"links   {len(have)} ({len(dangling)} dangling)")
    for r in dangling:
        print(f"  dangling: {r} -> {have[r]}")
    print(f"dirs    {len(dirs)} ({locked} locked{'' if locked == len(dirs) else ', NOT ALL LOCKED'})")
    print(f"foreign {len(foreign)}")
    cmd_plan(farm, src, layout, check=False)


def main():
    ap = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    ap.add_argument("command", choices=["update", "plan", "check", "status", "lock", "unlock"])
    ap.add_argument("--src", type=Path, default=Path.home() / "src")
    ap.add_argument("--farm", type=Path, default=Path.home() / "s")
    ap.add_argument("--layout", type=Path, default=HERE / "layout.conf")
    a = ap.parse_args()
    src, farm = a.src.expanduser().absolute(), a.farm.expanduser().absolute()
    if not src.is_dir():
        sys.exit(f"source {src} is not a directory")
    if farm == src or src in farm.parents or farm in src.parents:
        sys.exit("farm and source must be separate directories")
    if a.command == "update":
        cmd_update(farm, src, a.layout)
    elif a.command in ("plan", "check"):
        cmd_plan(farm, src, a.layout, check=a.command == "check")
    elif a.command == "status":
        cmd_status(farm, src, a.layout)
    else:
        guard(farm, src)
        set_locked(farm, a.command == "lock")
        print(f"{farm}: {a.command}ed")


if __name__ == "__main__":
    main()
